/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aglad
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnClick = new java.awt.Button();
        lblResultado = new java.awt.Label();
        btnMouse = new java.awt.Button();
        btnFoco = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnClick.setLabel("Click");
        btnClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClickActionPerformed(evt);
            }
        });
        getContentPane().add(btnClick);
        btnClick.setBounds(10, 30, 43, 24);

        lblResultado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblResultado.setText("Resultado");
        getContentPane().add(lblResultado);
        lblResultado.setBounds(20, 260, 360, 20);

        btnMouse.setLabel("Ao Paasar com Mouse");
        btnMouse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMouseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMouseMouseExited(evt);
            }
        });
        getContentPane().add(btnMouse);
        btnMouse.setBounds(100, 30, 140, 24);

        btnFoco.setLabel("Foco");
        btnFoco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnFocoFocusGained(evt);
            }
        });
        getContentPane().add(btnFoco);
        btnFoco.setBounds(290, 30, 43, 24);

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClickActionPerformed
        // TODO add your handling code here:
        
        lblResultado.setText("Click do botão");
    }//GEN-LAST:event_btnClickActionPerformed

    private void btnMouseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMouseMouseEntered
        // TODO add your handling code here:
        
        lblResultado.setText("O Mouse entrou na área do botão");
    }//GEN-LAST:event_btnMouseMouseEntered

    private void btnMouseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMouseMouseExited
        // TODO add your handling code here:
        
        lblResultado.setText("O Mouse saiu da área do botão");
    }//GEN-LAST:event_btnMouseMouseExited

    private void btnFocoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnFocoFocusGained
        // TODO add your handling code here:
        
        lblResultado.setText("O botão recebeu foco");
    }//GEN-LAST:event_btnFocoFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnClick;
    private java.awt.Button btnFoco;
    private java.awt.Button btnMouse;
    private java.awt.Label lblResultado;
    // End of variables declaration//GEN-END:variables
}
